import { billLineItems, bills } from "@vamp-bills/backend/db/app-schema.ts";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod";

// Auto-derived from Drizzle column shapes, with server-managed columns
// stripped. These never come from clients: `id` is generated by Postgres
// (`gen_random_uuid()::text`); `status` is owned by the state machine and
// only the spec'd transitions can change it; `createdBy` is filled from
// the authenticated session in the router; timestamps default in the DB.
// `billId` on line items is similarly server-linked after the bill insert.
//
// Used at tRPC mutation boundaries (bills.create, bills.update — future
// PR) and as the base shape for `readyBillSchema` below. Adding a column
// to `bills` in app-schema.ts flows through here automatically — but if
// it's a new server-managed column, add it to the omit list too.
const requiredText = (label: string) =>
  z
    .string()
    .trim()
    .min(1, { message: `${label} is required` });

const decimalAmount = z.string().regex(/^\d+(\.\d{1,2})?$/, {
  message: "must be a non-negative decimal with up to 2 fractional digits",
});

// MVP scope is USD-only (docs/mvp-scope.md). The Drizzle column has
// `default('USD')` and `notNull`, but text columns accept any string —
// pin to the literal here so non-USD currency is rejected at the
// *insert* layer too, not only at submit time. Otherwise drafts could
// be persisted with `currency: 'EUR'` even though they could never be
// successfully submitted.
const usdLiteral = z.literal("USD");

// FK + required-text refinements live here (not only on `readyBillSchema`)
// because the DB enforces them too — the FK columns are notNull text, so
// drizzle-zod produces `z.string()`, which silently accepts `""`. Without
// these refinements, `bills.create` accepts an empty `vendorId` /
// `approverId` and the insert fails at the FK boundary with a 500. Reject
// at the input layer, surface a sensible Zod error, no DB round-trip.
export const insertBillSchema = createInsertSchema(bills)
  .omit({
    id: true,
    status: true,
    createdBy: true,
    createdAt: true,
    updatedAt: true,
  })
  .extend({
    vendorId: requiredText("vendorId"),
    approverId: requiredText("approverId"),
    invoiceNumber: requiredText("invoiceNumber"),
    description: requiredText("description"),
    currency: usdLiteral,
    // Drizzle's `numeric` column maps to a relaxed `z.string()` from
    // drizzle-zod (Postgres returns numerics as strings, but no decimal
    // format is enforced). Without this extension a payload like
    // `totalAmount: 'abc'` slips through Zod and fails at the DB layer
    // as a 500. Pinning the format here closes the gap on `bills.create`
    // and on the draft-update path (drafts skip readiness, so the
    // readyBillSchema regex doesn't catch it there either).
    totalAmount: decimalAmount,
  });

export const insertLineItemSchema = createInsertSchema(billLineItems)
  .omit({
    id: true,
    billId: true,
    createdAt: true,
    updatedAt: true,
  })
  .extend({
    description: requiredText("description"),
    // Same `numeric` → relaxed `z.string()` gap as `bills.totalAmount`:
    // without this, `lineItems: [{ description: "x", amount: "sixty", ... }]`
    // sails through Zod and fails at the Postgres numeric column → 500.
    // Pin the decimal format at the input layer so client-side typos
    // surface as BAD_REQUEST.
    amount: decimalAmount,
  });

// "Ready to submit" — the spec's `Draft (Ready)` predicate. Layered on top of
// the column shapes with domain refinements that sit above the DB level
// (whitespace-only strings, decimal format, ≥1 line item, totals reconcile).
//
// Used by:
//  - the XState `isReady` guard (via the boolean wrapper below)
//  - the eventual `bills.submit` tRPC mutation (input validation + early reject)
//  - the eventual UI "what's blocking submit?" display (via `missingPaths`)
export const readyBillSchema = insertBillSchema
  .extend({
    // vendorId / approverId / invoiceNumber / description / currency /
    // totalAmount are already constrained on the insertBillSchema base.
    // What's added at the "ready" layer:
    //   - ≥1 line item, each fully validated,
    //   - line item amounts must reconcile with totalAmount (superRefine below).
    //
    // Description/amount per-item validation now lives on
    // `insertLineItemSchema`, but we restate the shape here so the
    // submit-time guard knows about line items as a unit and stays robust
    // if a future refactor changes how lineItems are spliced in.
    lineItems: z
      .array(
        z.object({
          description: requiredText("description"),
          amount: decimalAmount,
          position: z.number().int().nonnegative(),
        }),
      )
      .min(1, { message: "at least one line item is required" }),
  })
  .superRefine((bill, ctx) => {
    const totalCents = toCents(bill.totalAmount);
    const sumCents = bill.lineItems.reduce((acc, li) => acc + toCents(li.amount), 0);
    if (Number.isFinite(totalCents) && Number.isFinite(sumCents) && totalCents !== sumCents) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        path: ["totalAmount"],
        message: "totals_reconcile",
      });
    }
  });

export type ReadyBill = z.infer<typeof readyBillSchema>;

export type ReadinessLineItem = {
  description: string;
  amount: string;
  position: number;
};

export function isReady(bill: unknown): boolean {
  return readyBillSchema.safeParse(bill).success;
}

// Returns the list of top-level field paths that are blocking a "ready" parse.
// Output is `string[]` (Zod issue paths) — UI consumers can switch on the
// strings or narrow against `Object.keys(readyBillSchema.shape)` for an
// exhaustive check.
export function missingPaths(bill: unknown): string[] {
  const result = readyBillSchema.safeParse(bill);
  if (result.success) return [];
  // De-dupe: a field can have multiple issues (e.g. "is required" + nested
  // refine). Caller wants "which fields are blocking", not "how many issues".
  const paths = new Set<string>();
  for (const issue of result.error.issues) {
    const head = issue.path[0];
    if (head !== undefined) paths.add(String(head));
  }
  return [...paths];
}

// Sum line-item amounts as integer cents to avoid float drift on `numeric(12, 2)`
// strings from node-postgres. Empty/whitespace strings rejected up front so
// blank line items don't silently count as zero.
function toCents(amount: string): number {
  if (amount.trim() === "") return Number.NaN;
  const n = Number(amount);
  return Number.isFinite(n) ? Math.round(n * 100) : Number.NaN;
}
