import { billLineItems, bills } from "@vamp-bills/backend/db/app-schema.ts";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod";

// Auto-derived from Drizzle column shapes, with server-managed columns
// stripped. These never come from clients: `id` is generated by Postgres
// (`gen_random_uuid()::text`); `status` is owned by the state machine and
// only the spec'd transitions can change it; `createdBy` is filled from
// the authenticated session in the router; timestamps default in the DB.
// `billId` on line items is similarly server-linked after the bill insert.
//
// Used at tRPC mutation boundaries (bills.create, bills.update — future
// PR) and as the base shape for `readyBillSchema` below. Adding a column
// to `bills` in app-schema.ts flows through here automatically — but if
// it's a new server-managed column, add it to the omit list too.
export const insertBillSchema = createInsertSchema(bills).omit({
  id: true,
  status: true,
  createdBy: true,
  createdAt: true,
  updatedAt: true,
});
export const insertLineItemSchema = createInsertSchema(billLineItems).omit({
  id: true,
  billId: true,
  createdAt: true,
  updatedAt: true,
});

const requiredText = (label: string) =>
  z
    .string()
    .trim()
    .min(1, { message: `${label} is required` });

const decimalAmount = z.string().regex(/^\d+(\.\d{1,2})?$/, {
  message: "must be a non-negative decimal with up to 2 fractional digits",
});

// "Ready to submit" — the spec's `Draft (Ready)` predicate. Layered on top of
// the column shapes with domain refinements that sit above the DB level
// (whitespace-only strings, decimal format, ≥1 line item, totals reconcile).
//
// Used by:
//  - the XState `isReady` guard (via the boolean wrapper below)
//  - the eventual `bills.submit` tRPC mutation (input validation + early reject)
//  - the eventual UI "what's blocking submit?" display (via `missingPaths`)
export const readyBillSchema = insertBillSchema
  .extend({
    vendorId: requiredText("vendor"),
    approverId: requiredText("approver"),
    invoiceNumber: requiredText("invoice_number"),
    description: requiredText("description"),
    totalAmount: decimalAmount,
    // MVP scope is USD-only (docs/mvp-scope.md). The Drizzle column has
    // `default('USD')` and `notNull`, but text columns accept any string —
    // pin to the literal here so `bills.create({ currency: 'EUR' })` is
    // rejected at the schema layer rather than silently inserted.
    currency: z.literal("USD"),
    lineItems: z
      .array(
        z.object({
          description: z.string(),
          amount: decimalAmount,
          position: z.number().int().nonnegative(),
        }),
      )
      .min(1, { message: "at least one line item is required" }),
  })
  .superRefine((bill, ctx) => {
    const totalCents = toCents(bill.totalAmount);
    const sumCents = bill.lineItems.reduce((acc, li) => acc + toCents(li.amount), 0);
    if (Number.isFinite(totalCents) && Number.isFinite(sumCents) && totalCents !== sumCents) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        path: ["totalAmount"],
        message: "totals_reconcile",
      });
    }
  });

export type ReadyBill = z.infer<typeof readyBillSchema>;

export function isReady(bill: unknown): boolean {
  return readyBillSchema.safeParse(bill).success;
}

// Returns the list of top-level field paths that are blocking a "ready" parse.
// Output is `string[]` (Zod issue paths) — UI consumers can switch on the
// strings or narrow against `Object.keys(readyBillSchema.shape)` for an
// exhaustive check.
export function missingPaths(bill: unknown): string[] {
  const result = readyBillSchema.safeParse(bill);
  if (result.success) return [];
  // De-dupe: a field can have multiple issues (e.g. "is required" + nested
  // refine). Caller wants "which fields are blocking", not "how many issues".
  const paths = new Set<string>();
  for (const issue of result.error.issues) {
    const head = issue.path[0];
    if (head !== undefined) paths.add(String(head));
  }
  return [...paths];
}

// Sum line-item amounts as integer cents to avoid float drift on `numeric(12, 2)`
// strings from node-postgres. Empty/whitespace strings rejected up front so
// blank line items don't silently count as zero.
function toCents(amount: string): number {
  if (amount.trim() === "") return Number.NaN;
  const n = Number(amount);
  return Number.isFinite(n) ? Math.round(n * 100) : Number.NaN;
}
